name: Jira Integration

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
  pull_request:
    types: [opened, closed]

jobs:

  extract-jira:
    name: Extract Jira Issue
    runs-on: ubuntu-latest
    outputs:
      issue: ${{ steps.set-jira.outputs.issue }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Jira Issue Key
        id: set-jira
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ISSUE=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]+-[0-9]+')
          else
            ISSUE=$(git log -1 --pretty=%B | grep -oE '[A-Z]+-[0-9]+')
          fi

          if [[ -n "$ISSUE" ]]; then
            echo "issue=$ISSUE" >> $GITHUB_OUTPUT
          else
            echo "issue=" >> $GITHUB_OUTPUT
          fi

  jira-in-progress:
    name: Mark Jira as In Progress
    runs-on: ubuntu-latest
    needs: extract-jira
    if: github.event_name == 'pull_request' && github.event.action == 'opened' && needs.extract-jira.outputs.issue != ''
    steps:
      - name: Set In Progress in Jira
        run: |
          curl -X POST "https://shakal-express.atlassian.net/rest/api/3/issue/${{ needs.extract-jira.outputs.issue }}/transitions" \
            --user "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
            --header "Content-Type: application/json" \
            --data '{"transition": {"id": "31"}}'

  jira-comment:
    name: Add PR link to Jira
    runs-on: ubuntu-latest
    needs: extract-jira
    if: github.event_name == 'pull_request' && github.event.action == 'opened' && needs.extract-jira.outputs.issue != ''
    steps:
      - name: Add comment
        run: |
          curl -X POST "https://shakal-express.atlassian.net/rest/api/3/issue/${{ needs.extract-jira.outputs.issue }}/comment" \
            --user "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
            --header "Content-Type: application/json" \
            --data '{
              "body": "🔗 Pull Request: [${{ github.event.pull_request.html_url }}](${{ github.event.pull_request.html_url }})"
            }'

  jira-done:
    name: Mark Jira as Done
    runs-on: ubuntu-latest
    needs: extract-jira
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && needs.extract-jira.outputs.issue != ''
    steps:
      - name: Set Done in Jira
        run: |
          curl -X POST "https://shakal-express.atlassian.net/rest/api/3/issue/${{ needs.extract-jira.outputs.issue }}/transitions" \
            --user "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
            --header "Content-Type: application/json" \
            --data '{"transition": {"id": "51"}}'
