name: Jira Integration

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
  pull_request:
    types: [opened, closed]

jobs:

  extract-jira:
    name: Extract Jira Issue
    runs-on: ubuntu-latest
    outputs:
      issue: ${{ steps.set-jira.outputs.issue }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Jira Issue Key
        id: set-jira
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "issue=$(echo '${{ github.event.pull_request.title }}' | grep -oE '[A-Z]+-[0-9]+')" >> $GITHUB_OUTPUT
          else
            echo "issue=$(git log -1 --pretty=%B | grep -oE '[A-Z]+-[0-9]+')" >> $GITHUB_OUTPUT
          fi

  jira-in-progress:
    name: Mark Jira as In Progress
    runs-on: ubuntu-latest
    needs: extract-jira
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Set In Progress in Jira
        run: |
          curl -X POST "https://shakal-express.atlassian.net/rest/api/3/issue/${{ needs.extract-jira.outputs.issue }}/transitions" \
            --user "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
            --header "Content-Type: application/json" \
            --data '{"transition": {"id": "31"}}'

  jira-comment:
    name: Add PR link to Jira
    runs-on: ubuntu-latest
    needs: extract-jira
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Add comment
        run: |
          curl -X POST "https://shakal-express.atlassian.net/rest/api/3/issue/${{ needs.extract-jira.outputs.issue }}/comment" \
            --user "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
            --header "Content-Type: application/json" \
            --data '{
              "body": "🔗 Pull Request: [${{ github.event.pull_request.html_url }}](${{ github.event.pull_request.html_url }})"
            }'

  jira-done:
    name: Mark Jira as Done
    runs-on: ubuntu-latest
    needs: extract-jira
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    steps:
      - name: Set Done in Jira
        run: |
          curl -X POST "https://shakal-express.atlassian.net/rest/api/3/issue/${{ needs.extract-jira.outputs.issue }}/transitions" \
            --user "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN }}" \
            --header "Content-Type: application/json" \
            --data '{"transition": {"id": "51"}}'

  delete-branch:
    name: Delete merged branch
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      !startsWith(github.event.pull_request.head.ref, 'main') &&
      !startsWith(github.event.pull_request.head.ref, 'develop')
    steps:
      - name: Delete branch
        run: |
          BRANCH=${{ github.event.pull_request.head.ref }}
          echo "✅ Deleting remote branch: $BRANCH"
          curl -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH
